### ISSUE TITLE
公开出来这个有问题没有？

### ISSUE THREAD

**Issue by zhuangya** [zhuangya/nxmix-api#1]
cc @jacobbubu

**Comment by jacobbubu** [comment]
没问题。我自己都没想到做个 API。:thumbsup:

**Comment by zhuangya** [comment]
@jacobbubu 能提供一个用来测试的 partner key/secret 不

**Comment by jacobbubu** [comment]
你是说任何人都可以测试？那不就相当于不用申请了？  

Node with ☕️️.

Rong Shen

**Comment by zhuangya** [comment]
可以加 travis-ci 的 env 里面

**Comment by jacobbubu** [comment]
我明白了。审核的原因在于有些商业合作有排他的需求，因此需要我们审核一下，否则就可能违背了和客户的合约。我可以做一个公开测试的P/S，但是只能拿一周以前的数据
。

请先 Open 这个 Issue，我做好好了告诉你。

Node with ☕️️.

Rong Shen

**Comment by jacobbubu** [comment]
已经添加了 *******\* ***********************************************\* 作为测试。
返回的最新数据也是"今天"之前七天的。

https://github.com/NXMIX/nextday-public-api

**Comment by zhuangya** [comment]
囧 我是想你私下给我的来着，我已经加到 travis 里面去了
有时间我来写几个测试
